config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root "brands#index"
  match "/help",    to: "static_pages#help",    via: "get"
  match "/about",   to: "static_pages#about",   via: "get"
  match "/contact", to: "static_pages#contact", via: "get"
  resources :users
  resources :admins
  namespace :admin do
    resources :users
    resources :brands
    resources :categories
    resources :products
  end
  resources :brands
  resources :categories
  resources :products
  match "/users/:id/finish_signup", to: "users#finish_signup",
    via: [:get, :patch], as: :finish_signup

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products
  validates :name, presence: true
  attachment :avatar, content_type: ["image/jpeg", "image/png", "image/gif"]

  def file_name
    avatar_filename
  end
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < ApplicationController
  before_filter :authenticate_admin!
  load_and_authorize_resource param_method: :brand_params

  def show
    @brand = Brand.find params[:id]
  end

  def index
    @brands = Brand.all
    @brand = Brand.new
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new brand_params
    if @brand.save
      flash[:success] = "Created"
      redirect_to admin_brand_url(@brand)
    else
      render :new
    end
  end

  def edit
    @brand = Brand.find params[:id]
  end

  def update
    @brand = Brand.find params[:id]
    if @brand.update_attributes brand_params
      flash[:success] = "Updated"
      redirect_to admin_brands_url
    else
      render :edit
    end
  end

  def destroy
    @brand = Brand.find params[:id]
    @brand.destroy
    flash[:success] = "Deleted"
    redirect_to admin_brands_url
  end

  private
  def brand_params
    params.require(:brand).permit(:name, :avatar, :remove_avatar)
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  load_and_authorize_resource
end

app/views/admin/brands/_form.html.erb
<div class="row">
  <div class="span8 offset4">
    <%= form_for [:admin, @brand] do |f| %>
      <%= render "shared/errors", object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: "Name" %></br>
      <% if @brand.persisted? %>
      <div>
        <%= f.object.file_name %>
        <%= f.check_box :remove_avatar %>
      </div>
      <% end %>
      <%= f.label :avatar %>
      <%= f.attachment_field :avatar, direct: true, presigned: true %></br></br>
      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/brands/edit.html.erb
<h1>Edit Brand</h1>
<%= render "form" %>

app/views/admin/brands/index.html.erb
<%= provide(:title, "All Brands") %>
<h1>Create new brand</h1>
<%= render "form" %>

<ul class="brands">
  <% @brands.each do |brand| %>
    <li>
      <td><%= attachment_image_tag(brand, :avatar) %></td>
      <div>
        <%= link_to brand.name, admin_brand_path(brand) %>
      </div>
      <div>
        <%= link_to "Edit", edit_admin_brand_path(brand) %> |
        <%= link_to "Delete", admin_brand_path(brand), method: :delete,
          data: {confirm: "Are you sure?"} %>
      </div>
    </li>
  <% end %>
</ul>

app/views/admin/brands/new.html.erb
<h1>Create new brand</h1>
<%= render "form" %>

app/views/admin/brands/show.html.erb
<% provide(:title, @brand.name) %>
<h1><%= @brand.name %></h1>
<div class="center">
  <%= attachment_image_tag(@brand, :avatar) %>
</div>

<h2><%= link_to "Create new product", new_admin_product_path %></h2>
<h2>OR</h2>
<h2>Create product in this brand</h2>
<div class="row">
  <div class="span8 offset4">
    <%= form_for [:admin, Product.new] do |f| %>
      <%= render "shared/errors", object: f.object %>
      <%= f.hidden_field :brand_id, value: @brand.id %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "input-xlarge", required: true %></br>
      <%= f.label :description %>
      <%= f.text_area :description, class: "input-xlarge" %></br>
      <%= f.label :price %>
      <%= f.number_field :price, class: "input-xlarge", required: true %></br>
      <%= f.label :quantity %>
      <%= f.number_field :quantity, class: "input-xlarge", required: true %></br>
      <%= f.label :category %>
      <%= f.collection_select :category_id, Category.all, :id, :name,
        prompt: "Please pick a category" %></br>
      <%= f.label :image %>
      <%= f.file_field :image %></br>
      <%= f.label :bike_types %>
      <% Product::BIKE_TYPES.each do |bike_type| %>
        <%= f.check_box :bike_types, {multiple: true}, bike_type, nil %>
        <%= bike_type %>
      <% end %></br></br>
      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<strong>Products</strong>
<ul class="brands">
  <% @brand.products.each do |product| %>
    <li>
      <%= link_to image_tag(product.image.url(:thumb)), admin_product_path(product) %>
      <div><%= link_to product.name, admin_product_path(product) %></div>
      <div>
        <%= link_to "Edit", edit_admin_product_path(product) %> |
        <%= link_to "Delete", admin_product_path(product), method: :delete,
          data: {confirm: "Are you sure?"} %>
      </div>
    </li>
  <% end %>
</ul>