config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root "brands#index"
  match "/help",    to: "static_pages#help",    via: "get"
  match "/about",   to: "static_pages#about",   via: "get"
  match "/contact", to: "static_pages#contact", via: "get"
  resources :users
  resources :admins
  namespace :admin do
    resources :users
    resources :brands
    resources :categories
    resources :products
  end
  resources :brands
  resources :categories
  resources :products
  match "/users/:id/finish_signup", to: "users#finish_signup",
    via: [:get, :patch], as: :finish_signup

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_filter :authenticate_admin!
  load_and_authorize_resource param_method: :category_params
  
  def show
    @category = Category.find params[:id]
  end

  def index
    @categories = Category.all
    @category = Category.new
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "Created"
      redirect_to admin_category_url(@category)
    else
      render :new
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    if @category.update_attributes category_params
      flash[:success] = "Updated"
      redirect_to admin_categories_url
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find params[:id]
    @category.destroy
    flash[:success] = "Deleted"
    redirect_to admin_categories_url
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
end

app/views/admin/categories/_form.html.erb
<div class="row center">
  <div class="span6 offset3">
    <%= form_for [:admin, @category] do |f| %>
      <%= render "shared/errors", object: f.object %>
      <%= f.text_field :name, placeholder: "Name" %></br>
      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<h1>Edit Category</h1>
<%= render "form" %>

app/views/admin/categories/index.html.erb
<h1>Create new category</h1>
<%= render "form" %>

<ul class="categories">
  <% @categories.each do |category| %>
    <li>
      <%= link_to category.name, admin_category_path(category) %> |
      <%= link_to "Edit", edit_admin_category_path(category) %> |
      <%= link_to "Delete", admin_category_path(category), method: :delete,
        data: {confirm: "Are you sure?"} %>
    </li>
  <% end %>
</ul>

app/views/admin/categories/new.html.erb
<h1>Create new category</h1>
<%= render "form" %>

app/views/admin/categories/show.html.erb
<% provide(:title, @category.name) %>
<h1><%= @category.name %></h1>

<h2><%= link_to "Create new product", new_admin_product_path %></h2>
<h2>OR</h2>
<h2>Create product in this category</h2>
<div class="row">
  <div class="span8 offset4">
    <%= form_for [:admin, Product.new] do |f| %>
      <%= render "shared/errors", object: f.object %>
      <%= f.hidden_field :category_id, value: @category.id %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "input-xlarge", required: true %></br>
      <%= f.label :description %>
      <%= f.text_area :description, class: "input-xlarge" %></br>
      <%= f.label :price %>
      <%= f.number_field :price, class: "input-xlarge", required: true %></br>
      <%= f.label :quantity %>
      <%= f.number_field :quantity, class: "input-xlarge", required: true %></br>
      <%= f.label :image %>
      <%= f.file_field :image %></br>
      <%= f.label :brand %>
      <%= f.collection_select :brand_id, Brand.all, :id, :name, 
        prompt: "Please pick a brand" %></br>
      <%= f.label :bike_types %>
      <% Product::BIKE_TYPES.each do |bike_type| %>
        <%= f.check_box :bike_types, {multiple: true}, bike_type, nil %>
        <%= bike_type %>
      <% end %></br></br>
      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<strong>Products</strong>
<ul class="categories">
  <% @category.products.each do |product| %>
    <li>
      <%= link_to image_tag(product.image.url(:thumb)), admin_product_path(product) %>
      <div><%= link_to product.name, admin_product_path(product) %></div>
      <div>
        <%= link_to "Edit", edit_admin_product_path(product) %> |
        <%= link_to "Delete", admin_product_path(product), method: :delete,
          data: {confirm: "Are you sure?"} %>
      </div>
    </li>
  <% end %>
</ul>